#!/usr/bin/perl -w
use strict;
use warnings;

our $r2 = sqrt 2;

my %description;

if ($#ARGV == 0 and $ARGV[0] eq '-h') {
  print "USAGE: lv -h\n";
  print "       lv\n";
  print "       lv <lv> <iso>\n";
  print "\n10 is Sunny 16.";
}

while (<DATA>) {
  print if $#ARGV < 1;
  chomp;
  my ($k, $v) = split ' ', $_, 2;
  $description{$k} = $v;
}

if ($#ARGV < 1) {
  exit 1;
}

my ($lv, $iso) = @ARGV;

# We're counting 1/3 stops.

# We want ISO 100 to be 5, but it comes out as 6 2/3.
my $iso_e = sprintf '%.f', (3 * (log $iso)/(log 2))-5;

binmode STDOUT, ':utf8';

print "$lv $description{$lv}\n";
print "$iso ", vulgar($iso_e), "\n";

my $total = 3*$lv + $iso_e;
print "\n";

our %time = (
  8192 => 8000,
  4096 => 4000,
  2048 => 2000,
  1024 => 1000,
  512 => 500,
  256 => 250,
  128 => 125,
  64 => 60,
  32 => 30,
  16 => 15,
  8 => 8,
  4 => 4,
  2 => 2,
  1 => 1
);

for (my $i = 0; $i <= 10; $i += 1) {
  my $sv = ($total / 3) - $i;
  my $time = 2 ** $sv;
  if (exists $time{$time}) {
    $time = $time{$time};
  }
  if ($time > 1) {
    printf "f/%.1f 1/%s\n", $r2 ** $i, $time;
  } else {
    printf "f/%.1f %.f\"\n", $r2 ** $i, 1/$time;
  }
}

sub vulgar {
  my ($x) = @_;
  my $r = $x % 3;
  my $v = '   ';
  if ($r == 1) {
    # $v = "\x{2153}";
    $v = '1/3';
  } elsif ($r == 2) {
    # $v = "\x{2154}";
    $v = '2/3';
  }
  return sprintf "%d %s", int($x/3), $v;
}

# Outside, day
# High noon bright sun                         10
# Late afternoon sidelight                      9
# Overcast, high and bright, no shadows         8
#
#
# Dark, dreary overcast day in BOS, LON, CDG    5
#
#
# Bottom of rainforest canopy                   2

# Inside
# Office lighting                               2
# Bright home at night                          1
# Living room at night                          0

# Outside, night
# Sunset                                        6
#
# 10 minutes after sunset                       2

# The sky
# The moon (full-crescent)                      5-9

__DATA__
LV TYPE OF LIGHTING SITUATION
-11 Night, away from city lights, subject under starlight only.
-10 Night, away from city lights, subject under crescent moon.
-9 Night, away from city lights, subject under half moon. Meteors (during showers, with time exposure).
-8 Night, away from city lights, subject under full moon.
-7 Night, away from city lights, snowscape under full moon.
-6 Subjects lit by dim ambient artificial light.
-5 Subjects lit by dim ambient artificial light.
-4 Distant view of lighted skyline.
-3 Lightning (with time exposure). Total eclipse of moon.
-2 Fireworks (with time exposure).
-1 Candle lit close-ups. Christmas lights, floodlit buildings, fountains, and monuments. Subjects under bright street lamps.
0 Night home interiors, average light. School or church auditoriums. Subjects lit by campfires or bonfires.
1 Brightly lit home interiors at night. Fairs, amusement parks.
2 Office lighting. Bottom of rainforest canopy. Brightly lighted nighttime streets. Indoor sports. Stage shows, circuses.
3 Las Vegas or Times Square at night. Store windows. Campfires, bonfires, burning buildings. Ice shows, football, baseball etc. at night. Interiors with bright florescent lights.
4 Landscapes, city skylines 10 minutes after sunset. Neon lights, spotlighted subjects.
5 Landscapes and skylines immediately after sunset. Crescent moon (long lens).
6 Sunsets. Subjects in deep shade.
7 Half moon (long lens). Subject in open shade or heavy overcast.
8 Gibbous moon (long lens). Subjects in cloudy-bright light (no shadows).
9 Full moon (long lens). Subjects in weak, hazy sun.
10 Subjects in bright or hazy sun (Sunny f/16 rule).
11 Subjects in bright daylight on sand or snow.
12 Rarely encountered in nature. Some man made lighting.
13 Rarely encountered in nature. Some man made lighting.
14 Rarely encountered in nature. Some man made lighting.
15 Rarely encountered in nature. Some man made lighting.
16 Rarely encountered in nature. Some man made lighting.
17 Extremely bright. Rarely encountered in nature.
18 Extremely bright. Rarely encountered in nature.
